// Scene bookmarks IO: package the live bookmark list as a portable
// JSON envelope and parse one back. Kept as pure functions so the
// React panel stays focused on prompting / wiring; this module also
// catches the common-case footguns (wrong file format, schema bumps,
// over-sized payloads) before anything reaches the gallery state.
//
// Envelope shapes:
//   v1 (bookmarks only):
//     {
//       kind:    'ai-particle-simulator/scene-bookmarks',
//       v:       1,
//       exportedAt: ISO-8601 timestamp,
//       items:   [{ name, scene, createdAt? }, ...]
//     }
//   v2 (combined — bookmarks + saved camera views in one file):
//     {
//       kind:    'ai-particle-simulator/scene-bookmarks',
//       v:       2,
//       exportedAt: ISO-8601 timestamp,
//       items:   [{ name, scene, createdAt? }, ...],
//       views:   [{ name, pos, target, createdAt? }, ...]
//     }
//
// Ids are intentionally NOT serialised — they're regenerated by
// appendBookmark on import so the existing dedupe-by-name + monotonic
// id machinery keeps working.

import { appendBookmark, MAX_BOOKMARKS } from './sceneBookmarks.js'
import { appendView, CAMERA_VIEWS_MAX } from './cameraViews.js'

export const EXPORT_KIND = 'ai-particle-simulator/scene-bookmarks'
// Latest schema version. v2 adds an optional `views` array; v1 imports
// are still accepted and treated as views-less so old files keep working.
export const EXPORT_VERSION = 2
export const LEGACY_EXPORT_VERSION = 1

// Tightish cap so a malicious JSON can't blow up the browser.
// Bumped from 256KB to 384KB now that we also include the camera-view
// list — still well under any real-world bookmark+view collection.
export const MAX_IMPORT_BYTES = 384 * 1024

// Build the export envelope from the live bookmark list. Caller can
// pass any in-memory shape; we keep only the user-facing fields so
// future store-only metadata doesn't accidentally ship.
//
// When `views` is passed (non-empty array) the envelope is bumped to
// v2 and includes the views; otherwise we emit v1 for compatibility
// with older importers in third-party tooling people may have built.
export function buildExportPayload(items, nowIso = new Date().toISOString(), views = null) {
  const safeItems = Array.isArray(items) ? items : []
  const sanitizedViews = sanitizeViewsForExport(views)
  const includeViews = sanitizedViews.length > 0
  const env = {
    kind: EXPORT_KIND,
    v: includeViews ? EXPORT_VERSION : LEGACY_EXPORT_VERSION,
    exportedAt: nowIso,
    items: safeItems.map(it => ({
      name: typeof it.name === 'string' ? it.name : 'Untitled',
      createdAt: Number.isFinite(it.createdAt) ? it.createdAt : null,
      scene: it.scene && typeof it.scene === 'object' ? it.scene : {},
    })),
  }
  if (includeViews) env.views = sanitizedViews
  return env
}

// Whitelist + coerce each camera view entry the same way the renderer
// would — name strings, 3-tuple pos/target arrays, optional timestamp.
// Drops anything malformed instead of failing the whole export.
function sanitizeViewsForExport(views) {
  if (!Array.isArray(views)) return []
  const out = []
  for (const v of views) {
    if (!v || typeof v !== 'object') continue
    const name = typeof v.name === 'string' && v.name.trim()
      ? v.name.slice(0, 64)
      : null
    const pos = isVec3(v.pos) ? v.pos.slice(0, 3).map(Number) : null
    const target = isVec3(v.target) ? v.target.slice(0, 3).map(Number) : null
    if (!name || !pos || !target) continue
    const entry = { name, pos, target }
    if (Number.isFinite(v.createdAt)) entry.createdAt = v.createdAt
    out.push(entry)
  }
  return out
}

function isVec3(arr) {
  if (!Array.isArray(arr) || arr.length < 3) return false
  for (let i = 0; i < 3; i++) {
    if (!Number.isFinite(arr[i])) return false
  }
  return true
}

// Serialise the envelope as nicely-formatted JSON. Optional `views`
// argument graduates the file to a v2 combined envelope.
export function serializeBookmarks(items, views = null) {
  return JSON.stringify(buildExportPayload(items, undefined, views), null, 2)
}

// Build a "scenes-2026-06-20.json"-style file name. Pure helper so
// the React side doesn't have to mess with toISOString slicing.
// When `combined` is true we use a clearer "scenes+views-..." name
// so the user instantly sees the file holds both kinds of data.
export function makeFilename(nowIso = new Date().toISOString(), combined = false) {
  const date = nowIso.slice(0, 10)
  return combined
    ? `particle-scenes+views-${date}.json`
    : `particle-scenes-${date}.json`
}

// Parse a raw JSON string into a list of importable bookmarks.
// Returns { ok: true, items, views, source } on success, or
// { ok: false, error } when the file looks wrong. We do *not* mutate
// any caller state — the caller decides how to merge the result.
//
// `views` is always an array (possibly empty) so callers can iterate
// without a null-check. v1 envelopes are accepted with views=[].
export function parseImport(raw) {
  if (typeof raw !== 'string') {
    return { ok: false, error: 'Import data was not a string' }
  }
  if (raw.length > MAX_IMPORT_BYTES) {
    return { ok: false, error: `File too large (max ${(MAX_IMPORT_BYTES / 1024) | 0} KB)` }
  }
  let parsed
  try { parsed = JSON.parse(raw) }
  catch (e) { return { ok: false, error: `Invalid JSON: ${e.message || 'parse failed'}` } }
  if (!parsed || typeof parsed !== 'object') {
    return { ok: false, error: 'Top-level value must be an object' }
  }
  // Tolerate both the export envelope and a bare array of items —
  // makes hand-rolled / older exports work without ceremony.
  let envelope = parsed
  if (Array.isArray(parsed)) {
    envelope = { kind: EXPORT_KIND, v: LEGACY_EXPORT_VERSION, items: parsed }
  }
  if (envelope.kind && envelope.kind !== EXPORT_KIND) {
    return { ok: false, error: `Wrong file kind: ${envelope.kind}` }
  }
  if (envelope.v && envelope.v > EXPORT_VERSION) {
    return { ok: false, error: `Unsupported export version: ${envelope.v}` }
  }
  if (!Array.isArray(envelope.items)) {
    return { ok: false, error: '`items` array missing from envelope' }
  }
  // Whitelist + coerce each entry so a single bad row doesn't kill the import.
  const items = []
  for (const row of envelope.items) {
    if (!row || typeof row !== 'object') continue
    const name = typeof row.name === 'string' && row.name.trim()
      ? row.name.slice(0, 64)
      : null
    const scene = row.scene && typeof row.scene === 'object' ? row.scene : null
    if (!name || !scene) continue
    items.push({
      name,
      scene,
      createdAt: Number.isFinite(row.createdAt) ? row.createdAt : Date.now(),
    })
  }
  // Views are optional — a v1 file will not have them.
  const views = []
  if (Array.isArray(envelope.views)) {
    for (const row of envelope.views) {
      if (!row || typeof row !== 'object') continue
      const name = typeof row.name === 'string' && row.name.trim()
        ? row.name.slice(0, 64)
        : null
      if (!name || !isVec3(row.pos) || !isVec3(row.target)) continue
      views.push({
        name,
        pos: row.pos.slice(0, 3).map(Number),
        target: row.target.slice(0, 3).map(Number),
        createdAt: Number.isFinite(row.createdAt) ? row.createdAt : Date.now(),
      })
    }
  }
  if (items.length === 0 && views.length === 0) {
    return { ok: false, error: 'No valid bookmarks or views found in file' }
  }
  return { ok: true, items, views, source: envelope }
}

// Merge imported items into a live bookmark list. Dedupe by name
// (existing helper does the heavy lifting). Caller decides whether
// to replace or merge — `mode = 'merge'` keeps existing entries and
// only adds new names; `mode = 'replace'` drops the existing list
// and uses only the import. Returns the new list AND a summary so
// the UI can show "added N, replaced M, skipped K".
export function mergeImport(existing, imported, mode = 'merge') {
  if (!Array.isArray(imported)) return { items: existing || [], added: 0, replaced: 0, skipped: 0 }
  if (mode === 'replace') {
    let items = []
    let added = 0
    for (const it of imported) {
      const before = items.length
      items = appendBookmark(items, { name: it.name, scene: it.scene })
      if (items.length > before) added++
    }
    return { items, added, replaced: 0, skipped: imported.length - added }
  }
  // Merge: walk imported entries, skip names already present, append
  // the rest. Cap with MAX_BOOKMARKS via the existing append helper.
  let items = Array.isArray(existing) ? existing.slice() : []
  let added = 0, skipped = 0
  const seen = new Set(items.map(it => it.name))
  for (const it of imported) {
    if (seen.has(it.name)) { skipped++; continue }
    if (items.length >= MAX_BOOKMARKS) { skipped++; continue }
    items = appendBookmark(items, { name: it.name, scene: it.scene })
    seen.add(it.name)
    added++
  }
  return { items, added, replaced: 0, skipped }
}

// Mirror of mergeImport for the camera-view list. Same merge/replace
// semantics so the UI can give symmetrical feedback. Dedupes by name
// (cameraViews.appendView also dedupes by name on insert).
export function mergeImportViews(existing, imported, mode = 'merge') {
  if (!Array.isArray(imported)) return { views: existing || [], added: 0, replaced: 0, skipped: 0 }
  if (mode === 'replace') {
    let views = []
    let added = 0
    for (const v of imported) {
      const before = views.length
      views = appendView(views, { name: v.name, pos: v.pos, target: v.target })
      if (views.length > before) added++
    }
    return { views, added, replaced: 0, skipped: imported.length - added }
  }
  let views = Array.isArray(existing) ? existing.slice() : []
  let added = 0, skipped = 0
  const seen = new Set(views.map(v => v.name))
  for (const v of imported) {
    if (seen.has(v.name)) { skipped++; continue }
    if (views.length >= CAMERA_VIEWS_MAX) { skipped++; continue }
    views = appendView(views, { name: v.name, pos: v.pos, target: v.target })
    seen.add(v.name)
    added++
  }
  return { views, added, replaced: 0, skipped }
}

// Trigger a browser download of the JSON envelope. Returns the filename
// used, or null when something went wrong (e.g. no document context).
// Pass `views` (non-empty) to ship a combined v2 file.
export function downloadBookmarksFile(items, nowIso = new Date().toISOString(), views = null) {
  try {
    const json = serializeBookmarks(items, views)
    const blob = new Blob([json], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const sanitizedViews = sanitizeViewsForExport(views)
    const filename = makeFilename(nowIso, sanitizedViews.length > 0)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    // Revoke shortly after — Safari needs the URL alive across the
    // click tick before it can fetch.
    setTimeout(() => URL.revokeObjectURL(url), 1000)
    return filename
  } catch { return null }
}
