// Scene bookmarks IO: package the live bookmark list as a portable
// JSON envelope and parse one back. Kept as pure functions so the
// React panel stays focused on prompting / wiring; this module also
// catches the common-case footguns (wrong file format, schema bumps,
// over-sized payloads) before anything reaches the gallery state.
//
// Envelope shape (v1):
//   {
//     kind:    'ai-particle-simulator/scene-bookmarks',
//     v:       1,
//     exportedAt: ISO-8601 timestamp,
//     items:   [{ name, scene, createdAt? }, ...]
//   }
//
// Ids are intentionally NOT serialised — they're regenerated by
// appendBookmark on import so the existing dedupe-by-name + monotonic
// id machinery keeps working.

import { appendBookmark, MAX_BOOKMARKS } from './sceneBookmarks.js'

export const EXPORT_KIND = 'ai-particle-simulator/scene-bookmarks'
export const EXPORT_VERSION = 1

// Tightish cap so a malicious JSON can't blow up the browser.
// ~256KB is plenty for 12 bookmarks (real-world ~10KB total).
export const MAX_IMPORT_BYTES = 256 * 1024

// Build the export envelope from the live bookmark list. Caller can
// pass any in-memory shape; we keep only the user-facing fields so
// future store-only metadata doesn't accidentally ship.
export function buildExportPayload(items, nowIso = new Date().toISOString()) {
  const safeItems = Array.isArray(items) ? items : []
  return {
    kind: EXPORT_KIND,
    v: EXPORT_VERSION,
    exportedAt: nowIso,
    items: safeItems.map(it => ({
      name: typeof it.name === 'string' ? it.name : 'Untitled',
      createdAt: Number.isFinite(it.createdAt) ? it.createdAt : null,
      scene: it.scene && typeof it.scene === 'object' ? it.scene : {},
    })),
  }
}

// Serialise the envelope as nicely-formatted JSON.
export function serializeBookmarks(items) {
  return JSON.stringify(buildExportPayload(items), null, 2)
}

// Build a "scenes-2026-06-20.json"-style file name. Pure helper so
// the React side doesn't have to mess with toISOString slicing.
export function makeFilename(nowIso = new Date().toISOString()) {
  return `particle-scenes-${nowIso.slice(0, 10)}.json`
}

// Parse a raw JSON string into a list of importable bookmarks.
// Returns { ok: true, items, source } on success, or
// { ok: false, error } when the file looks wrong. We do *not* mutate
// any caller state — the caller decides how to merge the result.
export function parseImport(raw) {
  if (typeof raw !== 'string') {
    return { ok: false, error: 'Import data was not a string' }
  }
  if (raw.length > MAX_IMPORT_BYTES) {
    return { ok: false, error: `File too large (max ${(MAX_IMPORT_BYTES / 1024) | 0} KB)` }
  }
  let parsed
  try { parsed = JSON.parse(raw) }
  catch (e) { return { ok: false, error: `Invalid JSON: ${e.message || 'parse failed'}` } }
  if (!parsed || typeof parsed !== 'object') {
    return { ok: false, error: 'Top-level value must be an object' }
  }
  // Tolerate both the export envelope and a bare array of items —
  // makes hand-rolled / older exports work without ceremony.
  let envelope = parsed
  if (Array.isArray(parsed)) {
    envelope = { kind: EXPORT_KIND, v: EXPORT_VERSION, items: parsed }
  }
  if (envelope.kind && envelope.kind !== EXPORT_KIND) {
    return { ok: false, error: `Wrong file kind: ${envelope.kind}` }
  }
  if (envelope.v && envelope.v > EXPORT_VERSION) {
    return { ok: false, error: `Unsupported export version: ${envelope.v}` }
  }
  if (!Array.isArray(envelope.items)) {
    return { ok: false, error: '`items` array missing from envelope' }
  }
  // Whitelist + coerce each entry so a single bad row doesn't kill the import.
  const items = []
  for (const raw of envelope.items) {
    if (!raw || typeof raw !== 'object') continue
    const name = typeof raw.name === 'string' && raw.name.trim()
      ? raw.name.slice(0, 64)
      : null
    const scene = raw.scene && typeof raw.scene === 'object' ? raw.scene : null
    if (!name || !scene) continue
    items.push({
      name,
      scene,
      createdAt: Number.isFinite(raw.createdAt) ? raw.createdAt : Date.now(),
    })
  }
  if (items.length === 0) {
    return { ok: false, error: 'No valid bookmarks found in file' }
  }
  return { ok: true, items, source: envelope }
}

// Merge imported items into a live bookmark list. Dedupe by name
// (existing helper does the heavy lifting). Caller decides whether
// to replace or merge — `mode = 'merge'` keeps existing entries and
// only adds new names; `mode = 'replace'` drops the existing list
// and uses only the import. Returns the new list AND a summary so
// the UI can show "added N, replaced M, skipped K".
export function mergeImport(existing, imported, mode = 'merge') {
  if (!Array.isArray(imported)) return { items: existing || [], added: 0, replaced: 0, skipped: 0 }
  if (mode === 'replace') {
    let items = []
    let added = 0
    for (const it of imported) {
      const before = items.length
      items = appendBookmark(items, { name: it.name, scene: it.scene })
      if (items.length > before) added++
    }
    return { items, added, replaced: 0, skipped: imported.length - added }
  }
  // Merge: walk imported entries, skip names already present, append
  // the rest. Cap with MAX_BOOKMARKS via the existing append helper.
  let items = Array.isArray(existing) ? existing.slice() : []
  let added = 0, skipped = 0
  const seen = new Set(items.map(it => it.name))
  for (const it of imported) {
    if (seen.has(it.name)) { skipped++; continue }
    if (items.length >= MAX_BOOKMARKS) { skipped++; continue }
    items = appendBookmark(items, { name: it.name, scene: it.scene })
    seen.add(it.name)
    added++
  }
  return { items, added, replaced: 0, skipped }
}

// Trigger a browser download of the JSON envelope. Returns the filename
// used, or null when something went wrong (e.g. no document context).
export function downloadBookmarksFile(items, nowIso = new Date().toISOString()) {
  try {
    const json = serializeBookmarks(items)
    const blob = new Blob([json], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const filename = makeFilename(nowIso)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    // Revoke shortly after — Safari needs the URL alive across the
    // click tick before it can fetch.
    setTimeout(() => URL.revokeObjectURL(url), 1000)
    return filename
  } catch { return null }
}
